name: WhaleTunes
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.18.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.31 # Just Audio for audio streaming
  firebase_storage: ^11.0.13
  firebase_core: ^2.6.1
  google_fonts: ^4.0.3
  cloud_firestore: ^4.4.2
  firebase_auth: ^4.2.9
  font_awesome_flutter: ^10.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
